FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

WORKDIR /app

ENV ASPNETCORE_URLS=http://+:3003
ENV PAYMENT_APPROVAL_LIMIT=500

COPY publish/ .

EXPOSE 3003

ENTRYPOINT ["dotnet", "PaymentService.dll"]
